{{- if include "rackio.createSecret" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rackio.fullname" . }}
  labels:
    {{- include "rackio.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- with .Values.integrations.calibre.baseUrl }}
  CALIBRE_BASE_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.integrations.calibre.user }}
  CALIBRE_USER: {{ . | quote }}
  {{- end }}
  {{- with .Values.integrations.calibre.password }}
  CALIBRE_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- with .Values.integrations.calendar.icsUrl }}
  CALENDAR_ICS_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.integrations.adguard.baseUrl }}
  ADGUARD_BASE_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.integrations.adguard.user }}
  ADGUARD_USER: {{ . | quote }}
  {{- end }}
  {{- with .Values.integrations.adguard.password }}
  ADGUARD_PASSWORD: {{ . | quote }}
  {{- end }}
{{- end }}
