apiVersion: v1
kind: Service
metadata:
  name: {{ include "rackio.fullname" . }}
  labels:
    {{- include "rackio.labels" . | nindent 4 }}
  {{- $ann := merge (deepCopy .Values.service.annotations) (deepCopy .Values.commonAnnotations) }}
  {{- with $ann }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rackio.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
